# Generated by Django 4.2 on 2023-06-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customers_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='registration_time',
            field=models.CharField(max_length=255),
        ),
    ]
