# Generated by Django 4.2 on 2023-06-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_admin_categorys_maneger_products_orders_orderdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='category_image',
            field=models.CharField(max_length=9000),
        ),
    ]
