# Generated by Django 4.2 on 2023-06-25 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_categorys_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='category_image',
        ),
    ]
