# Generated by Django 4.2 on 2023-06-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_categorys_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
